apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: sayandev1998/microservices-learn-currency-exchange-service:0.0.13-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: microservices-learn-currency-exchange-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: spring.datasource.driver-class-name
            value: "org.postgresql.Driver"
          - name: spring.datasource.url
            value: "jdbc:postgresql://database-service:5432/postgres"
          - name: spring.datasource.username
            value: "admin"
          - name: spring.datasource.password
            value: "1234"
          - name: spring.jpa.show-sql
            value: "true"
          - name: spring.jpa.hibernate.ddl-auto
            value: "update"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  clusterIP: 10.8.6.152
  clusterIPs:
  - 10.8.6.152
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.192.122.187
